telegram:
  bot:
    token: <token>
    admin:
      chatId: <chatId>

accounts:
  ewelink:
    email: <email>
    password: <password>
  ipcam:
    login: <login>
    password: <password>

devices:
  shelly:
    d-1: shelly1-xxxxx
  sonoff:
    d-1: xxxxxxxx
    d-2: xxxxxxxx
  ipcam:
    d-1: xxxxxxxx

logging:
  level:
    root: INFO